spring:
  profiles.active: dev
  http.multipart.max-file-size: 10MB
  http.multipart.max-request-size: 11MB
  # real datasource is set programmatically
  datasource:
    url: jdbc:sqlite:/data.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect

---

spring:
  config:
    activate:
      on-profile: dev
  main:
    banner-mode: off

logging.level:
  root: INFO
  level: DEBUG
  org.springframework.web: DEBUG

---

spring:
  config:
    activate:
      on-profile: prod

logging.level:
  root: ERROR
  level: ERROR
  org.springframework.web: ERROR
