spring:
  profiles.active: dev

spring.http.multipart.max-file-size: 10MB
spring.http.multipart.max-request-size: 11MB

---

spring:
  config:
    activate:
      on-profile: dev
  main:
    banner-mode: off

logging.level:
  root: INFO
  level: DEBUG
  org.springframework.web: DEBUG

---

spring:
  config:
    activate:
      on-profile: prod

logging.level:
  root: ERROR
  level: ERROR
  org.springframework.web: ERROR
